"""Build the fresh-install D1 baseline from the immutable migration ledger."""

from __future__ import annotations

import argparse
import re
import sqlite3
import tempfile
from pathlib import Path

HEADER = """-- Generated by scripts/build_baseline_migration.py.
-- The migrations/ directory is the immutable historical ledger. New databases
-- use this baseline so a clean demo deployment starts from one migration.

PRAGMA foreign_keys = ON;
"""

SETUP_CREDENTIAL = """INSERT INTO instance_setup_credentials
  (singleton_key, deployment_key, generated_at_ms)
VALUES
  ('primary', lower(hex(randomblob(32))), unixepoch() * 1000);
"""

MIGRATION_NAME = re.compile(r"(?P<number>[0-9]{4})_[a-z0-9_]+\.sql")
SETUP_KEY = re.compile(r"[0-9a-f]{64}")


def migration_files(source: Path) -> list[Path]:
    files = sorted(source.glob("*.sql"))
    if not files:
        raise ValueError(f"no SQL migrations found in {source}")
    numbers: list[int] = []
    for migration in files:
        match = MIGRATION_NAME.fullmatch(migration.name)
        if match is None:
            raise ValueError(f"invalid migration filename: {migration.name}")
        numbers.append(int(match.group("number")))
    expected = list(range(1, len(files) + 1))
    if numbers != expected:
        raise ValueError(f"migration ledger must be contiguous; found {numbers}")
    return files


def apply_ledger(connection: sqlite3.Connection, source: Path) -> None:
    connection.execute("PRAGMA foreign_keys = ON")
    for migration in migration_files(source):
        connection.executescript(migration.read_text(encoding="utf-8"))
    validate_fresh_database(connection)


def validate_fresh_database(connection: sqlite3.Connection) -> None:
    violations = connection.execute("PRAGMA foreign_key_check").fetchall()
    if violations:
        raise ValueError(f"migration ledger violates foreign keys: {violations[:5]}")

    table_names = [
        str(row[0])
        for row in connection.execute(
            """SELECT name FROM sqlite_master
               WHERE type='table' AND name NOT LIKE 'sqlite_%'
               ORDER BY name"""
        ).fetchall()
    ]
    if "d1_migrations" in table_names:
        raise ValueError("migration ledger must not contain Wrangler's d1_migrations table")
    if "instance_setup_credentials" not in table_names:
        raise ValueError("migration ledger does not create instance_setup_credentials")

    credential_rows = connection.execute(
        """SELECT singleton_key,deployment_key
           FROM instance_setup_credentials"""
    ).fetchall()
    if (
        len(credential_rows) != 1
        or credential_rows[0][0] != "primary"
        or SETUP_KEY.fullmatch(str(credential_rows[0][1])) is None
    ):
        raise ValueError("fresh database must contain exactly one valid setup credential")

    populated: list[tuple[str, int]] = []
    for table_name in table_names:
        if table_name == "instance_setup_credentials":
            continue
        quoted_name = table_name.replace('"', '""')
        count = int(
            connection.execute(
                f'SELECT COUNT(*) FROM "{quoted_name}"'  # noqa: S608
            ).fetchone()[0]
        )
        if count:
            populated.append((table_name, count))
    if populated:
        raise ValueError(f"fresh database contains business data: {populated}")


def schema_statements(connection: sqlite3.Connection) -> list[str]:
    rows = connection.execute(
        """SELECT type,name,sql
           FROM sqlite_master
           WHERE sql IS NOT NULL
             AND name NOT LIKE 'sqlite_%'
             AND name != 'd1_migrations'
           ORDER BY CASE type
             WHEN 'table' THEN 1
             WHEN 'view' THEN 2
             WHEN 'index' THEN 3
             WHEN 'trigger' THEN 4
             ELSE 5 END,
             name"""
    ).fetchall()
    return [f"{str(sql).rstrip().rstrip(';')};" for _, _, sql in rows]


def render(source: Path) -> str:
    with tempfile.TemporaryDirectory(prefix="sessionbuddy-baseline-") as directory:
        database = Path(directory) / "baseline.sqlite3"
        connection = sqlite3.connect(database)
        try:
            apply_ledger(connection, source)
            statements = schema_statements(connection)
        finally:
            connection.close()
    return "\n\n".join([HEADER.rstrip(), *statements, SETUP_CREDENTIAL.rstrip()]) + "\n"


def build(source: Path, output: Path, *, check: bool = False) -> None:
    generated = render(source)
    if check:
        additive = sorted(path for path in output.parent.glob("*.sql") if path != output)
        if additive:
            with tempfile.TemporaryDirectory(prefix="sessionbuddy-baseline-check-") as directory:
                ledger_db = sqlite3.connect(Path(directory) / "ledger.sqlite3")
                baseline_db = sqlite3.connect(Path(directory) / "baseline.sqlite3")
                try:
                    apply_ledger(ledger_db, source)
                    baseline_db.execute("PRAGMA foreign_keys = ON")
                    for migration in sorted(output.parent.glob("*.sql")):
                        baseline_db.executescript(migration.read_text(encoding="utf-8"))
                    validate_fresh_database(baseline_db)
                    matches = schema_statements(ledger_db) == schema_statements(baseline_db)
                finally:
                    ledger_db.close()
                    baseline_db.close()
        else:
            matches = output.is_file() and output.read_text(encoding="utf-8") == generated
        if not matches:
            raise ValueError(
                f"{output.parent} is stale; reconcile it with the immutable migration ledger"
            )
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generated, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=Path("migrations"))
    parser.add_argument(
        "--output", type=Path, default=Path("migrations_baseline/0001_baseline.sql")
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in baseline does not match the migration ledger",
    )
    arguments = parser.parse_args()
    build(arguments.source, arguments.output, check=arguments.check)


if __name__ == "__main__":
    main()
